#[tool.flit.metadata]
#dist-name = "ynab-csv-converter"
#module = "ynab_csv_converter"

[tool.poetry]
name = "ynab-csv-converter"
version = "1.0.1"
description = "A simple CSV-based YNAB converter"
authors = ["Anders Ingemann <anders@ingemann.de>"]
license = "Apache-2.0"
homepage = "https://github.com/andsens/ynab-csv-converter"
classifiers = [
  "Topic :: Utilities",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "License :: OSI Approved :: MIT License",
]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = ">=3.10"
docopt = ">=0.6.1"
jsonschema = ">=2.3.0"
openpyxl = "^3.0.10"
pandas = "^1.4.4"
pydantic = "^2.3.0"

[tool.poetry.dev-dependencies]
tox = "^3.26.0"
flake8 = "^5.0.4"

[tool.python.scripts]
ynab-csv-converter = "ynab_csv_converter.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
